# 배열 만들기

In [157]:
import numpy as np

## .array

### 1차원 배열

In [158]:
np.array([1,2,3], dtype='int32')

array([1, 2, 3], dtype=int32)

### 2차원 배열

In [159]:
np.array(([1,2,3,],[4,5,6]))

array([[1, 2, 3],
       [4, 5, 6]])

### 3차원 배열

In [160]:
np.array(([[1,2,3,],[4,5,6]],[[7,8,9],[10,11,12]]))

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

## .arange

시작과 끝, step을 지정해줄 수 있다. 그러면 numpy가 알아서 넣어준다.

In [161]:
np.arange(10,20,2)

array([10, 12, 14, 16, 18])

## .linespace

시작과 끝, 원소의 개수를 지정하면 원소간 균등한 거리로 생성된다.

In [162]:
np.linspace(1,10,10, dtype='int16')

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10], dtype=int16)

## .zeros, .ones, .full

range 지정해주는 것도 귀찮다. 모양만 지정해주자.

In [163]:
np.zeros((3,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [164]:
np.ones((3,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

같은 숫자를 넣는것도 가능하다.

In [165]:
np.full((3,5),5)

array([[5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5]])

<br>

<br>

# 배열 모양 바꾸기

## .reshape

In [166]:
a = np.arange(24)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [167]:
a.reshape(2,12)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23]])

In [168]:
a.reshape(2,3,4)

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [169]:
a = np.arange(12)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [170]:
a.reshape(-1)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [171]:
a.reshape(-1,1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11]])

In [172]:
a.reshape(-1,2)

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

In [173]:
a.reshape(-1,3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [174]:
a.reshape(-2,2,3)

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])

## .T(Transpose)

In [175]:
a = np.arange(6).reshape(2,3)
a

array([[0, 1, 2],
       [3, 4, 5]])

In [176]:
a.T

array([[0, 3],
       [1, 4],
       [2, 5]])

<br>

<br>

# 배열 합치기

## 1차원

In [177]:
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [178]:
np.concatenate((a,a), axis=None)

array([0, 1, 2, 3, 4, 0, 1, 2, 3, 4])

In [179]:
np.concatenate((a,a), axis=0)

array([0, 1, 2, 3, 4, 0, 1, 2, 3, 4])

In [180]:
np.hstack((a,a))

array([0, 1, 2, 3, 4, 0, 1, 2, 3, 4])

In [181]:
np.vstack((a,a))

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

In [182]:
np.stack((a,a), axis=0)

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

In [183]:
np.stack((a,a), axis=1)

array([[0, 0],
       [1, 1],
       [2, 2],
       [3, 3],
       [4, 4]])

In [184]:
np.dstack((a,a))

array([[[0, 0],
        [1, 1],
        [2, 2],
        [3, 3],
        [4, 4]]])

## 2차원

In [185]:
a = np.arange(6).reshape(2,3)
a

array([[0, 1, 2],
       [3, 4, 5]])

In [186]:
np.concatenate((a,a), axis=None)

array([0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5])

In [187]:
np.concatenate((a,a), axis=0)

array([[0, 1, 2],
       [3, 4, 5],
       [0, 1, 2],
       [3, 4, 5]])

In [188]:
np.concatenate((a,a), axis=1)

array([[0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5]])

In [189]:
np.hstack((a,a))

array([[0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5]])

In [190]:
np.vstack((a,a))

array([[0, 1, 2],
       [3, 4, 5],
       [0, 1, 2],
       [3, 4, 5]])

In [191]:
np.stack((a,a), axis=0)

array([[[0, 1, 2],
        [3, 4, 5]],

       [[0, 1, 2],
        [3, 4, 5]]])

In [192]:
np.stack((a,a), axis=1)

array([[[0, 1, 2],
        [0, 1, 2]],

       [[3, 4, 5],
        [3, 4, 5]]])

In [193]:
np.dstack((a,a))

array([[[0, 0],
        [1, 1],
        [2, 2]],

       [[3, 3],
        [4, 4],
        [5, 5]]])

<br>

<br>

# 배열 나누기

## 1차원

In [194]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [195]:
np.array_split(a,2,axis=0)

[array([0, 1, 2, 3, 4]), array([5, 6, 7, 8, 9])]

In [196]:
np.hsplit(a,2)

[array([0, 1, 2, 3, 4]), array([5, 6, 7, 8, 9])]

## 2차원

In [197]:
a = np.arange(12).reshape(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [198]:
np.array_split(a,3,axis=0)

[array([[0, 1, 2, 3]]), array([[4, 5, 6, 7]]), array([[ 8,  9, 10, 11]])]

In [199]:
np.vsplit(a,3)

[array([[0, 1, 2, 3]]), array([[4, 5, 6, 7]]), array([[ 8,  9, 10, 11]])]

In [200]:
np.array_split(a,2,axis=1)

[array([[0, 1],
        [4, 5],
        [8, 9]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11]])]

In [201]:
np.hsplit(a,2)

[array([[0, 1],
        [4, 5],
        [8, 9]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11]])]