# 배열 만들기

In [36]:
import numpy as np

간단하게 배열이랑 배열의 차원, shape를 print하는 함수만들어서 생성할 때마다 실행해보자.

In [37]:
def my_info(a):
    # print('a:       ',a)
    print(a)
    print('-'*30)
    print('차원:     ',a.ndim)
    print('shape:   ',a.shape)
    # print('-'*50)
    print('')
    # print('')

## numpy.array

### 1차원 배열

In [38]:
a = np.array([1,2,3], dtype='int32')
my_info(a)

[1 2 3]
------------------------------
차원:      1
shape:    (3,)



### 2차원 배열

In [39]:
a = np.array(([1,2,3,],[4,5,6]))
my_info(a)

[[1 2 3]
 [4 5 6]]
------------------------------
차원:      2
shape:    (2, 3)



### 3차원 배열

In [40]:
a = np.array(([[1,2,3,],[4,5,6]],[[7,8,9],[10,11,12]]))
my_info(a)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
------------------------------
차원:      3
shape:    (2, 2, 3)



## numpy.arange

시작과 끝, step을 지정해줄 수 있다. 그러면 numpy가 알아서 넣어준다.

In [41]:
a = np.arange(10,20,2)
my_info(a)

[10 12 14 16 18]
------------------------------
차원:      1
shape:    (5,)



## numpy.linespace

시작과 끝, 원소의 개수를 지정하면 원소간 균등한 거리로 생성된다.

In [42]:
a = np.linspace(1,10,10, dtype='int16')
my_info(a)

[ 1  2  3  4  5  6  7  8  9 10]
------------------------------
차원:      1
shape:    (10,)



## numpy.zeros & numpy.ones & numpy.full

range 지정해주는 것도 귀찮다. 모양만 지정해주자.

In [43]:
a = np.zeros((3,5))
my_info(a)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
------------------------------
차원:      2
shape:    (3, 5)



In [44]:
a = np.ones((3,5))
my_info(a)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
------------------------------
차원:      2
shape:    (3, 5)



같은 숫자를 넣는것도 가능하다.

In [45]:
a = np.full((3,5),5)
my_info(a)

[[5 5 5 5 5]
 [5 5 5 5 5]
 [5 5 5 5 5]]
------------------------------
차원:      2
shape:    (3, 5)



<br>

<br>

# 배열 모양 바꾸기

## numpy.reshape

In [46]:
a = np.arange(10)
my_info(a)

[0 1 2 3 4 5 6 7 8 9]
------------------------------
차원:      1
shape:    (10,)



In [47]:
b = a.reshape(2,5)
my_info(b)

[[0 1 2 3 4]
 [5 6 7 8 9]]
------------------------------
차원:      2
shape:    (2, 5)



In [48]:
b = a.reshape(-1,1)
my_info(b)

[[0]
 [1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]
------------------------------
차원:      2
shape:    (10, 1)



In [49]:
b = b.reshape(-1,2)
my_info(b)

[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]
------------------------------
차원:      2
shape:    (5, 2)



## numpy.T(Transpose)

In [50]:
a = np.arange(20).reshape(2,10)
my_info(a)

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]]
------------------------------
차원:      2
shape:    (2, 10)



In [51]:
a.T

array([[ 0, 10],
       [ 1, 11],
       [ 2, 12],
       [ 3, 13],
       [ 4, 14],
       [ 5, 15],
       [ 6, 16],
       [ 7, 17],
       [ 8, 18],
       [ 9, 19]])

<br>

<br>

# 배열 합치기

## numpy.vstack & numpy.hstack & numpy.dstack

concatenate보다 이게 더 직관적이다.

concatenate는 아래에서...

### 1차원

In [52]:
a = np.arange(10)
my_info(a)

[0 1 2 3 4 5 6 7 8 9]
------------------------------
차원:      1
shape:    (10,)



In [53]:
b = np.hstack((a,a))
my_info(b)

[0 1 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9]
------------------------------
차원:      1
shape:    (20,)



In [54]:
c = np.vstack((a,a))
my_info(c)

[[0 1 2 3 4 5 6 7 8 9]
 [0 1 2 3 4 5 6 7 8 9]]
------------------------------
차원:      2
shape:    (2, 10)



In [55]:
d = np.dstack((a,a))
my_info(d)

[[[0 0]
  [1 1]
  [2 2]
  [3 3]
  [4 4]
  [5 5]
  [6 6]
  [7 7]
  [8 8]
  [9 9]]]
------------------------------
차원:      3
shape:    (1, 10, 2)



### 2차원

In [80]:
a = np.arange(10).reshape(2,5)
my_info(a)

[[0 1 2 3 4]
 [5 6 7 8 9]]
------------------------------
차원:      2
shape:    (2, 5)



In [57]:
b = np.hstack((a,a))
my_info(b)

[[0 1 2 3 4 0 1 2 3 4]
 [5 6 7 8 9 5 6 7 8 9]]
------------------------------
차원:      2
shape:    (2, 10)



In [58]:
c = np.vstack((a,a))
my_info(c)

[[0 1 2 3 4]
 [5 6 7 8 9]
 [0 1 2 3 4]
 [5 6 7 8 9]]
------------------------------
차원:      2
shape:    (4, 5)



In [59]:
d = np.dstack((a,a))
my_info(d)

[[[0 0]
  [1 1]
  [2 2]
  [3 3]
  [4 4]]

 [[5 5]
  [6 6]
  [7 7]
  [8 8]
  [9 9]]]
------------------------------
차원:      3
shape:    (2, 5, 2)



## numpy.concatenate

In [60]:
a = np.arange(10).reshape(2,5)
my_info(a)

[[0 1 2 3 4]
 [5 6 7 8 9]]
------------------------------
차원:      2
shape:    (2, 5)



In [61]:
b = np.concatenate((a,a),axis=0) # np.vstack((a,a))
my_info(b)

[[0 1 2 3 4]
 [5 6 7 8 9]
 [0 1 2 3 4]
 [5 6 7 8 9]]
------------------------------
차원:      2
shape:    (4, 5)



In [62]:
b = np.concatenate((a,a),axis=1) # np.hstack((a,a))
my_info(b)

[[0 1 2 3 4 0 1 2 3 4]
 [5 6 7 8 9 5 6 7 8 9]]
------------------------------
차원:      2
shape:    (2, 10)



In [69]:
x = np.arange(5)
x

array([0, 1, 2, 3, 4])

In [73]:
np.hstack((x,x))

array([0, 1, 2, 3, 4, 0, 1, 2, 3, 4])

In [74]:
np.vstack((x,x))

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

In [76]:
np.dstack((x,x))

array([[[0, 0],
        [1, 1],
        [2, 2],
        [3, 3],
        [4, 4]]])