배열의 원소를 select해보자.

[공식문서](https://numpy.org/doc/stable/user/basics.indexing.html)

In [1]:
import numpy as np

<br>

<br>

In [5]:
a = np.full((5,5),1)
a

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [9]:
a = np.arange(20).reshape(4,5)
print(a)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
