# 랜덤은 언제나 랜덤인가?

In [1]:
from numpy import random

### 0 ~ 100 사이의 랜덤 정수

In [16]:
x = random.randint(100)
for i in range(3):
    print(x)

14
14
14


### 랜덤 부동 소수점

In [15]:
x = random.rand()
for i in range(3):
    print(x)

0.8130438048744185
0.8130438048744185
0.8130438048744185


In [17]:
x = random.randint(100, size=(3, 5))
print(x)

[[33 92 51 13 66]
 [52 57 12 73 83]
 [67 17 31 36 19]]
